# Generated by Django 4.2.4 on 2023-11-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, unique=True)),
                ("quantity", models.IntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
