# Generated by Django 4.2.4 on 2023-11-21 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LearningHub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("thumbnail_url", models.CharField(max_length=100)),
                (
                    "course_type",
                    models.CharField(
                        choices=[("FREE", "FREE"), ("PAID", "PAID")],
                        default="FREE",
                        max_length=4,
                    ),
                ),
                ("course_length", models.CharField(max_length=20)),
                ("course_slug", models.SlugField(default="-")),
                ("course_price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lecture_images/"
                    ),
                ),
                ("video_url", models.CharField(max_length=100)),
                ("lecture_slug", models.SlugField(default="-")),
                (
                    "lecture_type",
                    models.CharField(
                        choices=[
                            ("PREMIUM", "Premium"),
                            ("NOT PREMIUM", "Not Premium"),
                        ],
                        default="PREMIUM",
                        max_length=12,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LearningHub.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LectureComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LearningHub.lecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LearningHub.course",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="session_year_id",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="subject_id",
        ),
        migrations.RemoveField(
            model_name="attendancereport",
            name="attendance_id",
        ),
        migrations.RemoveField(
            model_name="attendancereport",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="feedbackstaffs",
            name="staff_id",
        ),
        migrations.RemoveField(
            model_name="feedbackstudent",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="leavereportstaff",
            name="staff_id",
        ),
        migrations.RemoveField(
            model_name="leavereportstudent",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="notificationstaffs",
            name="stafff_id",
        ),
        migrations.RemoveField(
            model_name="notificationstudent",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="staffs",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="studentresult",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="studentresult",
            name="subject_id",
        ),
        migrations.RemoveField(
            model_name="students",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="students",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="students",
            name="session_year_id",
        ),
        migrations.RemoveField(
            model_name="subjects",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="subjects",
            name="staff_id",
        ),
        migrations.DeleteModel(
            name="AdminHOD",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="AttendanceReport",
        ),
        migrations.DeleteModel(
            name="Courses",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="FeedBackStaffs",
        ),
        migrations.DeleteModel(
            name="FeedBackStudent",
        ),
        migrations.DeleteModel(
            name="LeaveReportStaff",
        ),
        migrations.DeleteModel(
            name="LeaveReportStudent",
        ),
        migrations.DeleteModel(
            name="NotificationStaffs",
        ),
        migrations.DeleteModel(
            name="NotificationStudent",
        ),
        migrations.DeleteModel(
            name="SessionYearModel",
        ),
        migrations.DeleteModel(
            name="Staffs",
        ),
        migrations.DeleteModel(
            name="StudentResult",
        ),
        migrations.DeleteModel(
            name="Students",
        ),
        migrations.DeleteModel(
            name="Subjects",
        ),
        migrations.AddField(
            model_name="lecture",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="LearningHub.section"
            ),
        ),
    ]
